server:
  port: 0
  
spring:
  cloud:
    stream:
      bindings:
        consumer-in-0:
          destination: KFP-STREAM
  kafka:
    bootstrap-servers:
    - "localhost:9092"
    
spring.cloud.stream.kafka.bindings.consumer-in-0:
  consumer:
    configuration:
      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer
