server:
  port: 0
  
spring:
  kafka:
    listener:
      type: batch
    consumer:
      max-poll-records: 10
      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"
        
